### PR TITLE
Add Japanese blog post about RSEAA

### PR DESCRIPTION
**Pull request by kozo2**
This PR is simply a Japanese translation of https://github.com/rse-asia/RSE_Asia/tree/main/_blog/2022-10-01-RSEAAExp22 .
This post has no content yet.
However, since my native language is Japanese, I thought it would be easier to write a post in Japanese and then translate it into English, so I created this template first.

### CODE REVIEW

**Comment by SaranjeetKaur** [comment]
This is so cool, @kozo2!

**Comment by SaranjeetKaur** [comment]
@joelnitta please review this PR! Thanks again for offering your help!

CC: @kozo2

**Comment by joelnitta** [comment]
FYI: I cannot render the website either from `main` or this PR (#50). I suspect the problem likely happened on `main` and still exists on this branch. So while I can address linguistic issues I cannot comment on technical aspects until #50 is resolved.

**Comment by SaranjeetKaur** [comment]
Hi @kozo2 and @joelnitta,

Apologies for the extreme delay in coming back to this!  
I will attempt to merge this PR for now as I am working on updating the overall website. However, please feel to open new issues/PRs for the things that are unaddressed here.
Thank you so much for your work on this!

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @joelnitta for review, content, translation

**Pull request merged**
