### PR TITLE
Add a Japanese translation of Home.

### PR DESCRIPTION
**Pull request by kozo2**

### CODE REVIEW

**Comment by SaranjeetKaur** [comment]
@annefou -- can we find a Japanese proficient reviewer for this pull request?

**Comment by SaranjeetKaur** [comment]
Thank you so much @annefou!

**Comment by naoe-tatara** [comment]
Yes, I thought that if the page was made and published yesterday, then it should be in the future form, but probably tomorrow at latest, this should be changed to past form :)

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @kozo2 for translation

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @annefou for mentoring, review, question

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @naoe-tatara for review, question

**Comment by kozo2** [comment]
I'm sorry, but please allow me to withdraw this PR.
The reason is that the upstream `main` branch has been updated, so now it's `aboutus.Rmd` (or some other pages) instead of `index.Rmd` that needs to be translated.

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @naoe-tatara for review, question

**Pull request closed without merging**
